name: Setup Bun
on: [ pull_request ]
jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v0.1.8
      - run: bun wiptest

